"""
exporter.py - PDF and CSV export utilities using reportlab and pandas.
"""
from __future__ import annotations
import io
import csv
from typing import List, Dict, Any

import pandas as pd
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT


def export_csv(trace: List[Dict[str, Any]]) -> bytes:
    """Serialize simulation trace as CSV bytes."""
    if not trace:
        return b""
    df = pd.DataFrame(trace)
    return df.to_csv(index=False).encode("utf-8")


def export_pdf(
    config: Dict[str, Any],
    metrics: Dict[str, Any],
    trace: List[Dict[str, Any]],
    comparison: List[Dict[str, Any]] | None = None,
) -> bytes:
    """Generate a professional PDF report using reportlab."""

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=2 * cm,
        leftMargin=2 * cm,
        topMargin=2 * cm,
        bottomMargin=2 * cm,
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "Title",
        parent=styles["Title"],
        fontSize=22,
        textColor=colors.HexColor("#1e40af"),
        spaceAfter=6,
        alignment=TA_CENTER,
    )
    h2_style = ParagraphStyle(
        "H2",
        parent=styles["Heading2"],
        fontSize=14,
        textColor=colors.HexColor("#1e3a8a"),
        spaceBefore=14,
        spaceAfter=4,
    )
    body_style = ParagraphStyle(
        "Body",
        parent=styles["Normal"],
        fontSize=10,
        leading=14,
    )

    story = []

    # ── Title ────────────────────────────────────────────────────────────────
    story.append(Paragraph("Cache Memory Simulation Report", title_style))
    story.append(Paragraph("Generated by Cache Memory Simulator & Policy Analyzer", body_style))
    story.append(Spacer(1, 0.4 * cm))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#93c5fd")))
    story.append(Spacer(1, 0.4 * cm))

    # ── Configuration ────────────────────────────────────────────────────────
    story.append(Paragraph("Cache Configuration", h2_style))
    cfg_data = [["Parameter", "Value"]] + [
        [k.replace("_", " ").title(), str(v)] for k, v in config.items()
    ]
    cfg_table = Table(cfg_data, colWidths=[8 * cm, 8 * cm])
    cfg_table.setStyle(_table_style())
    story.append(cfg_table)
    story.append(Spacer(1, 0.4 * cm))

    # ── Metrics ──────────────────────────────────────────────────────────────
    story.append(Paragraph("Performance Metrics", h2_style))
    m = metrics
    metric_data = [
        ["Metric", "Value"],
        ["Total Accesses", str(m.get("total_accesses", "-"))],
        ["Hits", str(m.get("hits", "-"))],
        ["Misses", str(m.get("misses", "-"))],
        ["Hit Rate", f"{float(m.get('hit_rate', 0)) * 100:.2f}%"],
        ["Miss Rate", f"{float(m.get('miss_rate', 0)) * 100:.2f}%"],
        ["AMAT (cycles)", str(m.get("amat", "-"))],
        ["CPI", str(m.get("cpi", "-"))],
    ]
    metric_table = Table(metric_data, colWidths=[8 * cm, 8 * cm])
    metric_table.setStyle(_table_style(highlight_col=1))
    story.append(metric_table)
    story.append(Spacer(1, 0.4 * cm))

    # ── Policy Comparison ────────────────────────────────────────────────────
    if comparison:
        story.append(Paragraph("Policy Comparison", h2_style))
        comp_headers = ["Policy", "Hits", "Misses", "Hit Rate", "AMAT", "CPI"]
        comp_data = [comp_headers] + [
            [
                r.get("policy", "-"),
                str(r.get("hits", "-")),
                str(r.get("misses", "-")),
                f"{float(r.get('hit_rate', 0)) * 100:.2f}%",
                str(r.get("amat", "-")),
                str(r.get("cpi", "-")),
            ]
            for r in comparison
        ]
        comp_table = Table(comp_data, colWidths=[2.5 * cm, 2.5 * cm, 2.5 * cm, 2.5 * cm, 2.5 * cm, 2.5 * cm])
        comp_table.setStyle(_table_style())
        story.append(comp_table)
        story.append(Spacer(1, 0.4 * cm))

    # ── Access Trace (first 50 rows) ─────────────────────────────────────────
    story.append(Paragraph("Access Trace (first 50 entries)", h2_style))
    if trace:
        trace_headers = ["Tick", "Address", "Tag", "Set", "Offset", "Result", "Evicted"]
        trace_data = [trace_headers] + [
            [
                str(row.get("tick", "")),
                str(row.get("address", "")),
                str(row.get("tag", "")),
                str(row.get("set_index", "")),
                str(row.get("block_offset", "")),
                row.get("result", ""),
                str(row.get("evicted_tag", "-") or "-"),
            ]
            for row in trace[:50]
        ]
        col_w = [1.5 * cm, 3 * cm, 2 * cm, 1.5 * cm, 2 * cm, 2 * cm, 2 * cm]
        trace_table = Table(trace_data, colWidths=col_w)
        trace_table.setStyle(_trace_table_style())
        story.append(trace_table)

    story.append(Spacer(1, 0.5 * cm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.grey))
    story.append(Spacer(1, 0.2 * cm))
    story.append(Paragraph("Cache Memory Simulator — Computer Architecture Project", body_style))

    doc.build(story)
    return buffer.getvalue()


def _table_style(highlight_col: int | None = None) -> TableStyle:
    cmds = [
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e40af")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 10),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.HexColor("#f0f9ff"), colors.white]),
        ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 1), (-1, -1), 9),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#93c5fd")),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]
    return TableStyle(cmds)


def _trace_table_style() -> TableStyle:
    return TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e3a8a")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 7),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.HexColor("#f8fafc"), colors.white]),
        ("GRID", (0, 0), (-1, -1), 0.25, colors.lightgrey),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
    ])
